version: "3"
services:
  #Node App Service
  app:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    restart: on-failure
    depends_on:
      - "db"
      - "prisma"
    env_file: .env
    ports:
      - "88:5000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - /home/node/app/node_modules

  #React Client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: on-failure
    depends_on:
      - "app"
    env_file: .env
    ports:
      - "80:3000"
    volumes:
      - ./client:/home/node/app
      - /home/node/app/node_modules
      - /home/node/app/.next

  #Prisma Service for graphql
  prisma:
    build:
      context: ./app/prisma
      dockerfile: Dockerfile.dev
    restart: on-failure
    depends_on:
      - "db"
    ports:
      - "4466:4466"
    environment:
      PRISMA_MANAGEMENT_API_JWT_SECRET: ${PRISMA_SECRET}
      PRISMA_CONFIG_PATH: home/prisma-config.yml

  #Postgres DB
  db:
    image: "postgres:12"
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PG_PRIMARY_PORT: ${DB_PORT}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"

  #PGadmin service
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: on-failure
    depends_on:
      - "db"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80"

#Volumes
volumes:
  postgres:
  pgadmin:
